// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyBanTraGopXeHonda.Data;

#nullable disable

namespace QuanLyBanTraGopXeHonda.Migrations
{
    [DbContext(typeof(QLBXDbContext))]
    [Migration("20260208123853_KhoiTaoCSDL")]
    partial class KhoiTaoCSDL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyBanTraGopXeHonda.Data.HangXe", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TenHX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("HangXes");
                });

            modelBuilder.Entity("QuanLyBanTraGopXeHonda.Data.HopDong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("KhachHangID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLapHD")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<int>("XeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KhachHangID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("HopDongs");
                });

            modelBuilder.Entity("QuanLyBanTraGopXeHonda.Data.HopDong_ChiTiet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("HopDongID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoThangThanhToan")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("XeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("HopDongID");

                    b.HasIndex("XeID");

                    b.ToTable("HopDong_ChiTiets");
                });

            modelBuilder.Entity("QuanLyBanTraGopXeHonda.Data.KhachHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CCCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("QuanLyBanTraGopXeHonda.Data.LoaiXe", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TenLX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("LoaiXes");
                });

            modelBuilder.Entity("QuanLyBanTraGopXeHonda.Data.NhanVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("QuyenHan")
                        .HasColumnType("bit");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("QuanLyBanTraGopXeHonda.Data.Xe", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HangXeID")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiXeID")
                        .HasColumnType("int");

                    b.Property<string>("MauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NamSanXuat")
                        .HasColumnType("int");

                    b.Property<string>("SoKhung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoLuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoMay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenXe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("HangXeID");

                    b.HasIndex("LoaiXeID");

                    b.ToTable("Xes");
                });

            modelBuilder.Entity("QuanLyBanTraGopXeHonda.Data.HopDong", b =>
                {
                    b.HasOne("QuanLyBanTraGopXeHonda.Data.KhachHang", "KhachHang")
                        .WithMany("HopDong")
                        .HasForeignKey("KhachHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBanTraGopXeHonda.Data.NhanVien", "NhanVien")
                        .WithMany("HopDong")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyBanTraGopXeHonda.Data.HopDong_ChiTiet", b =>
                {
                    b.HasOne("QuanLyBanTraGopXeHonda.Data.HopDong", "HopDong")
                        .WithMany("HopDong_ChiTiet")
                        .HasForeignKey("HopDongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBanTraGopXeHonda.Data.Xe", "Xe")
                        .WithMany("HopDong_ChiTiet")
                        .HasForeignKey("XeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HopDong");

                    b.Navigation("Xe");
                });

            modelBuilder.Entity("QuanLyBanTraGopXeHonda.Data.Xe", b =>
                {
                    b.HasOne("QuanLyBanTraGopXeHonda.Data.HangXe", "HangXe")
                        .WithMany("Xe")
                        .HasForeignKey("HangXeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBanTraGopXeHonda.Data.LoaiXe", "LoaiXe")
                        .WithMany("Xe")
                        .HasForeignKey("LoaiXeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangXe");

                    b.Navigation("LoaiXe");
                });

            modelBuilder.Entity("QuanLyBanTraGopXeHonda.Data.HangXe", b =>
                {
                    b.Navigation("Xe");
                });

            modelBuilder.Entity("QuanLyBanTraGopXeHonda.Data.HopDong", b =>
                {
                    b.Navigation("HopDong_ChiTiet");
                });

            modelBuilder.Entity("QuanLyBanTraGopXeHonda.Data.KhachHang", b =>
                {
                    b.Navigation("HopDong");
                });

            modelBuilder.Entity("QuanLyBanTraGopXeHonda.Data.LoaiXe", b =>
                {
                    b.Navigation("Xe");
                });

            modelBuilder.Entity("QuanLyBanTraGopXeHonda.Data.NhanVien", b =>
                {
                    b.Navigation("HopDong");
                });

            modelBuilder.Entity("QuanLyBanTraGopXeHonda.Data.Xe", b =>
                {
                    b.Navigation("HopDong_ChiTiet");
                });
#pragma warning restore 612, 618
        }
    }
}
